-- =====================================
-- INSERT SAMPLE DATA
-- =====================================

-- Insert Leave Types
INSERT INTO LMS_LEAVE_TYPES
VALUES (LMS_LEAVE_TYPE_SEQ.NEXTVAL,'Annual Leave',30,'Y','Y');

-- =====================================
-- Insert Employee Leave Balance
-- =====================================

INSERT INTO LMS_EMP_LEAVE_BALANCE
(BALANCE_ID,EMP_ID,LEAVE_TYPE_ID,YEAR,TOTAL_ALLOCATED,USED_DAYS)
VALUES (LMS_BALANCE_SEQ.NEXTVAL,1,1,2025,30,0);

INSERT INTO LMS_EMP_LEAVE_BALANCE
(BALANCE_ID,EMP_ID,LEAVE_TYPE_ID,YEAR,TOTAL_ALLOCATED,USED_DAYS)
VALUES (LMS_BALANCE_SEQ.NEXTVAL,2,1,2025,30,0);

INSERT INTO LMS_EMP_LEAVE_BALANCE
(BALANCE_ID,EMP_ID,LEAVE_TYPE_ID,YEAR,TOTAL_ALLOCATED,USED_DAYS)
VALUES (LMS_BALANCE_SEQ.NEXTVAL,3,1,2025,30,0);

INSERT INTO LMS_EMP_LEAVE_BALANCE
(BALANCE_ID,EMP_ID,LEAVE_TYPE_ID,YEAR,TOTAL_ALLOCATED,USED_DAYS)
VALUES (LMS_BALANCE_SEQ.NEXTVAL,4,1,2025,30,0);

-- =====================================
-- Insert Leave Request
-- =====================================

INSERT INTO LMS_LEAVE_REQUESTS
(REQUEST_ID,EMP_ID,LEAVE_TYPE_ID,START_DATE,END_DATE,TOTAL_DAYS,STATUS)
VALUES
(LMS_REQ_SEQ.NEXTVAL,1,1,DATE '2025-06-01',DATE '2025-06-05',5,'PENDING');

COMMIT;