

CREATE OR REPLACE PROCEDURE LMS_REQUEST_LEAVE
(
    P_EMP_ID NUMBER,
    P_LEAVE_TYPE_ID NUMBER,
    P_START_DATE DATE,
    P_END_DATE DATE
)
IS
    V_TOTAL_DAYS NUMBER;
    V_REMAINING NUMBER;
BEGIN

    V_TOTAL_DAYS := P_END_DATE - P_START_DATE + 1;

    SELECT REMAINING_DAYS
    INTO V_REMAINING
    FROM LMS_EMP_LEAVE_BALANCE
    WHERE EMP_ID = P_EMP_ID
    AND LEAVE_TYPE_ID = P_LEAVE_TYPE_ID;

    IF V_REMAINING < V_TOTAL_DAYS THEN
        RAISE_APPLICATION_ERROR(-20001,'Leave balance not enough');
    END IF;

    INSERT INTO LMS_LEAVE_REQUESTS
    VALUES
    (
        LMS_REQUESR_SEQ.NEXTVAL,
        P_EMP_ID,
        P_LEAVE_TYPE_ID,
        P_START_DATE,
        P_END_DATE,
        V_TOTAL_DAYS,
        'PENDING',
        SYSDATE
    );

END;

---------------------------------


CREATE OR REPLACE PROCEDURE LMS_APPROVE_LEAVE
(
    P_REQUEST_ID NUMBER
)
IS
BEGIN

    UPDATE LMS_LEAVE_REQUESTS
    SET STATUS = 'APPROVED'
    WHERE REQUEST_ID = P_REQUEST_ID;

END;

---------------------------------------------------------

CREATE OR REPLACE PROCEDURE LMS_REJECT_LEAVE
(
    P_REQUEST_ID NUMBER
)
IS
BEGIN

UPDATE LMS_LEAVE_REQUESTS
SET STATUS = 'REJECTED'
WHERE REQUEST_ID = P_REQUEST_ID;

END;

---------------------------------------


CREATE OR REPLACE PROCEDURE APPROVE_LEAVE
(
P_REQUEST_ID NUMBER
)
IS
BEGIN

UPDATE LMS_LEAVE_REQUESTS
SET STATUS = 'APPROVED'
WHERE REQUEST_ID = P_REQUEST_ID;

UPDATE LMS_EMP_LEAVE_BALANCE
SET USED_DAYS = USED_DAYS +
(
SELECT TOTAL_DAYS 
FROM LMS_LEAVE_REQUESTS
WHERE REQUEST_ID = P_REQUEST_ID
)
WHERE EMP_ID =
(
SELECT EMP_ID 
FROM LMS_LEAVE_REQUESTS
WHERE REQUEST_ID = P_REQUEST_ID
);

COMMIT;

END;
/

--------------------------------

---------التشغيل

BEGIN
APPROVE_LEAVE(2);
END;
/


