
-- Employee Sequence
CREATE SEQUENCE LMS_EMP_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Leave Type Sequence
CREATE SEQUENCE LMS_LEAVE_TYPE_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Leave Request Sequence
CREATE SEQUENCE LMS_LEAVE_REQ_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Leave Balance Sequence
CREATE SEQUENCE LMS_BALANCE_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Department Sequence
CREATE SEQUENCE LMS_DEPT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Manager Approval Sequence
CREATE SEQUENCE LMS_APPROVAL_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;