create SEQUENCE LMS_EMP_SEQ START WITH 1 INCREMENT BY 1 ;
create SEQUENCE LMS_LEAVE_TYPE START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE LMS_BALANCE_SEQ START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE LMS_REQUESR_SEQ START WITH 1 INCREMENT BY 1;



CREATE TABLE LMS_EMPLOYEES (
 EMP_ID NUMBER PRIMARY KEY ,
 EMP_NAME VARCHAR2(100) NOT NULL ,
 HIRE_DATE DATE NOT NULL ,
 DEPT_NAME VARCHAR2(100) , 
 STATUS VARCHAR2(40) DEFAULT 'ACTIVE'
 );




CREATE TABLE LMS_LEAVE_TYPES (
LEAVE_TYPE_ID NUMBER PRIMARY KEY,
LEAVE_NAME VARCHAR2(50) NOT NULL,
MAX_DAY_PER_YEAR NUMBER NOT NULL,
IS_PAID CHAR(1) CHECK (IS_PAID IN ('Y','N')),
IS_ACTIVE CHAR(1) DEFAULT 'Y'
);




CREATE TABLE LMS_EMP_LEAVE_BALANCE (
    BALANCE_ID NUMBER PRIMARY KEY,
    EMP_ID NUMBER,
    LEAVE_TYPE_ID NUMBER,
    YEAR NUMBER,
    TOTAL_ALLOCATED NUMBER,
    USED_DAYS NUMBER DEFAULT 0,
    REMAINING_DAYS GENERATED ALWAYS AS 
        (TOTAL_ALLOCATED - USED_DAYS) VIRTUAL,
    CONSTRAINT FK_BAL_EMP FOREIGN KEY (EMP_ID)
        REFERENCES LMS_EMPLOYEES(EMP_ID),
    CONSTRAINT FK_BAL_TYPE FOREIGN KEY (LEAVE_TYPE_ID)
        REFERENCES LMS_LEAVE_TYPES(LEAVE_TYPE_ID)
);




CREATE TABLE LMS_LEAVE_REQUESTS (
    REQUEST_ID NUMBER PRIMARY KEY,
    EMP_ID NUMBER,
    LEAVE_TYPE_ID NUMBER,
    START_DATE DATE,
    END_DATE DATE,
    TOTAL_DAYS NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    REQUEST_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT FK_REQ_EMP FOREIGN KEY (EMP_ID)
        REFERENCES LMS_EMPLOYEES(EMP_ID),

    CONSTRAINT FK_REQ_TYPE FOREIGN KEY (LEAVE_TYPE_ID)
        REFERENCES LMS_LEAVE_TYPES(LEAVE_TYPE_ID)
);

