
CREATE OR REPLACE TRIGGER LMS_DEDUCT_LEAVE
AFTER UPDATE OF STATUS ON LMS_LEAVE_REQUESTS
FOR EACH ROW
WHEN (NEW.STATUS = 'APPROVED')
BEGIN

UPDATE LMS_EMP_LEAVE_BALANCE
SET USED_DAYS = USED_DAYS + :NEW.TOTAL_DAYS
WHERE EMP_ID = :NEW.EMP_ID
AND LEAVE_TYPE_ID = :NEW.LEAVE_TYPE_ID;

END

---------------------------------------------------------


CREATE OR REPLACE TRIGGER LMS_CHECK_BALANCE
BEFORE INSERT ON LMS_LEAVE_REQUESTS
FOR EACH ROW
DECLARE
    V_REMAINING NUMBER;
BEGIN

    SELECT REMAINING_DAYS
    INTO V_REMAINING
    FROM LMS_EMP_LEAVE_BALANCE
    WHERE EMP_ID = :NEW.EMP_ID
    AND LEAVE_TYPE_ID = :NEW.LEAVE_TYPE_ID;

    IF V_REMAINING < :NEW.TOTAL_DAYS THEN
        RAISE_APPLICATION_ERROR(-20002,'Not enough leave balance');
    END IF;

END;

-----------------------------------------------------------


CREATE OR REPLACE TRIGGER LMS_CALC_DAYS
BEFORE INSERT ON LMS_LEAVE_REQUESTS
FOR EACH ROW
BEGIN

:NEW.TOTAL_DAYS := :NEW.END_DATE - :NEW.START_DATE + 1;

END;

-------------------------------------------------
