
CREATE VIEW HR_LEAVE_REPORT AS
SELECT 
E.EMP_NAME,
L.LEAVE_NAME,
R.START_DATE,
R.END_DATE,
R.TOTAL_DAYS,
R.STATUS
FROM LMS_LEAVE_REQUESTS R
JOIN LMS_EMPLOYEES E
ON R.EMP_ID = E.EMP_ID
JOIN LMS_LEAVE_TYPES L
ON R.LEAVE_TYPE_ID = L.LEAVE_TYPE_ID;